// prime_hunter.c — a twin-prime hunter that reports to Telegram.
//
// The loop is ours this time: no LLM, no tools, no agent. Search upward for
// twin primes (p, p+2), announce a record when the gap between consecutive
// pairs beats the standing record, and send a heartbeat on a timer so the
// channel shows progress even during a long dry stretch.
//
// Written to compile unchanged in two places:
//   *nix:       gcc -O2 -o prime_hunter prime_hunter.c -lcurl
//   BareMetal:  cp prime_hunter.c BareMetal-App/ && ./1-build.sh prime_hunter.c
//
// BareMetal notes, from reading BareMetal-AppPort's own curltest.c/wiki_discord.c:
//   - there is no environment there, so every getenv() below falls back to the
//     #defines. Set them before building the unikernel.
//   - TLS needs the CA bundle named explicitly: /etc/ssl/cacert.pem on disk.img,
//     or the copy compiled into the binary as cacert_pem/cacert_pem_len.
//   - no cJSON dependency on purpose. Every string we send is generated by this
//     program out of digits and plain ASCII, so snprintf is enough and it's one
//     less ported library between us and a working microVM.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>
#include <unistd.h>
#include <curl/curl.h>

// ---------------------------------------------------------------- config
// getenv wins where there is one; these are what BareMetal builds compile in.

#define TELEGRAM_TOKEN_DEFAULT  "PUT_BOT_TOKEN_HERE"
#define TELEGRAM_CHAT_DEFAULT   "PUT_CHAT_ID_HERE"

// All three are -D overridable, so a build can be retuned without editing this
// file: gcc -DHEARTBEAT_SECONDS=60 ...
#ifndef START_AT
#define START_AT           1ULL      // first candidate k for the pair (6k-1, 6k+1).
#endif                               // Every twin pair except (3,5) has that shape,
                                     // so k=1 -> (5,7) is the true beginning.
#ifndef HEARTBEAT_SECONDS
#define HEARTBEAT_SECONDS  1800      // progress report cadence
#endif
#ifndef HEARTBEAT_EVERY
#define HEARTBEAT_EVERY    50000000ULL  // ...or this many candidates, whichever
#endif                                  // comes first. Belt and braces: if the
                                        // BareMetal clock misbehaves, progress
                                        // reports still go out.
#ifndef RECORD_FLOOR
#define RECORD_FLOOR       250ULL    // Silence floor for record announcements.
#endif                               // From a cold start every early gap is a
                                     // record — 6, then 12, then 18 — which would
                                     // fire a dozen messages in the first second.
                                     // Below this, records are tracked but not
                                     // announced.
#define HTTP_TIMEOUT       30L       // matches net_shim.c's own per-call cap
#define CA_BUNDLE_PATH     "/etc/ssl/cacert.pem"
#define USER_AGENT         "BareMetal-PrimeHunter/1.0"

// Provided by build/cacert_data.o in a BareMetal link; absent (and therefore
// zero-length) in an ordinary *nix build, where libcurl's own default CA store
// is used instead. Same two-source pattern as curltest.c.
__attribute__((weak)) const unsigned char cacert_pem[1];
__attribute__((weak)) const unsigned int  cacert_pem_len;

// ---------------------------------------------------------------- primality
//
// Deterministic Miller-Rabin. The 12-base witness set below is proven correct
// for every n < 2^64, so there is no probabilistic fudge here: a number this
// says is prime, is prime.

static uint64_t mulmod(uint64_t a, uint64_t b, uint64_t m) {
    return (uint64_t)((__uint128_t)a * b % m);   // x86-64 does this in one op
}

static uint64_t powmod(uint64_t base, uint64_t exp, uint64_t m) {
    uint64_t result = 1;
    base %= m;
    while (exp) {
        if (exp & 1) result = mulmod(result, base, m);
        base = mulmod(base, base, m);
        exp >>= 1;
    }
    return result;
}

static int is_prime(uint64_t n) {
    if (n < 2) return 0;
    for (uint64_t p = 2; p < 38; p++) {          // small primes by trial
        if (p * p > n) return 1;
        if (n % p == 0) return n == p;
    }

    uint64_t d = n - 1;
    int r = 0;
    while ((d & 1) == 0) { d >>= 1; r++; }

    static const uint64_t witnesses[] = {2,3,5,7,11,13,17,19,23,29,31,37};
    for (size_t i = 0; i < sizeof(witnesses)/sizeof(witnesses[0]); i++) {
        uint64_t a = witnesses[i] % n;
        if (a == 0) continue;

        uint64_t x = powmod(a, d, n);
        if (x == 1 || x == n - 1) continue;

        int composite = 1;
        for (int j = 1; j < r; j++) {
            x = mulmod(x, x, n);
            if (x == n - 1) { composite = 0; break; }
        }
        if (composite) return 0;
    }
    return 1;
}

// ---------------------------------------------------------------- telegram

static const char *g_token;
static const char *g_chat;
static char        g_url[512];
static long        g_posts_ok, g_posts_failed;

static size_t discard_cb(void *p, size_t size, size_t nmemb, void *userp) {
    (void)p; (void)userp;
    return size * nmemb;     // Telegram's reply is of no use to us
}

static void set_ca_bundle(CURL *h) {
    FILE *f = fopen(CA_BUNDLE_PATH, "r");
    if (f) {
        fclose(f);
        curl_easy_setopt(h, CURLOPT_CAINFO, CA_BUNDLE_PATH);
    } else if (cacert_pem_len > 0) {
        struct curl_blob blob = { (void *)cacert_pem, cacert_pem_len, CURL_BLOB_NOCOPY };
        curl_easy_setopt(h, CURLOPT_CAINFO_BLOB, &blob);
    }
    // Neither present: an ordinary *nix build, where libcurl already knows
    // where the system CA store lives.
}

// Escape the few characters JSON forbids in a string. Our text is generated
// from digits and plain ASCII, so this is belt and braces — but it costs
// nothing and means a stray character can never produce a 400.
static void json_escape(const char *in, char *out, size_t out_sz) {
    size_t o = 0;
    for (const unsigned char *p = (const unsigned char *)in; *p && o + 7 < out_sz; p++) {
        switch (*p) {
            case '"':  out[o++] = '\\'; out[o++] = '"';  break;
            case '\\': out[o++] = '\\'; out[o++] = '\\'; break;
            case '\n': out[o++] = '\\'; out[o++] = 'n';  break;
            case '\r': out[o++] = '\\'; out[o++] = 'r';  break;
            case '\t': out[o++] = '\\'; out[o++] = 't';  break;
            default:
                if (*p < 0x20) o += (size_t)snprintf(out + o, out_sz - o, "\\u%04x", *p);
                else           out[o++] = (char)*p;
        }
    }
    out[o] = '\0';
}

// Returns 1 on success. A failed send is never fatal: the hunt is the point,
// and the next report will carry the same news plus whatever came after it.
static int telegram_send(const char *text) {
    CURL *h = curl_easy_init();
    if (!h) return 0;

    static char escaped[4096];
    static char payload[4608];
    json_escape(text, escaped, sizeof(escaped));
    int n = snprintf(payload, sizeof(payload),
                     "{\"chat_id\":\"%s\",\"text\":\"%s\"}", g_chat, escaped);
    if (n < 0 || (size_t)n >= sizeof(payload)) { curl_easy_cleanup(h); return 0; }

    struct curl_slist *hdrs = curl_slist_append(NULL, "Content-Type: application/json");

    curl_easy_setopt(h, CURLOPT_URL, g_url);
    curl_easy_setopt(h, CURLOPT_POST, 1L);
    curl_easy_setopt(h, CURLOPT_POSTFIELDS, payload);
    curl_easy_setopt(h, CURLOPT_POSTFIELDSIZE, (long)n);
    curl_easy_setopt(h, CURLOPT_HTTPHEADER, hdrs);
    curl_easy_setopt(h, CURLOPT_WRITEFUNCTION, discard_cb);
    curl_easy_setopt(h, CURLOPT_USERAGENT, USER_AGENT);
    curl_easy_setopt(h, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(h, CURLOPT_TIMEOUT, HTTP_TIMEOUT);
    curl_easy_setopt(h, CURLOPT_SSL_VERIFYPEER, 1L);
    curl_easy_setopt(h, CURLOPT_SSL_VERIFYHOST, 2L);
    set_ca_bundle(h);

    CURLcode res = curl_easy_perform(h);
    long status = 0;
    curl_easy_getinfo(h, CURLINFO_RESPONSE_CODE, &status);
    curl_slist_free_all(hdrs);
    curl_easy_cleanup(h);

    if (res != CURLE_OK) {
        fprintf(stderr, "[!] telegram: %s\n", curl_easy_strerror(res));
        g_posts_failed++;
        return 0;
    }
    if (status >= 400) {
        fprintf(stderr, "[!] telegram: HTTP %ld\n", status);
        g_posts_failed++;
        return 0;
    }
    g_posts_ok++;
    // Say so out loud. On a headless microVM the serial console is the only
    // window into whether the network actually works, and "no error appeared"
    // is a much weaker claim than "the send was acknowledged".
    printf("[+] telegram ok (%ld sent, %ld failed)\n", g_posts_ok, g_posts_failed);
    return 1;
}

// ---------------------------------------------------------------- formatting

// 1234567 -> "1,234,567". Three digits at a time from the right.
static const char *commas(uint64_t v, char *buf, size_t sz) {
    char digits[24];
    int n = snprintf(digits, sizeof(digits), "%llu", (unsigned long long)v);
    size_t o = 0;
    for (int i = 0; i < n && o + 2 < sz; i++) {
        if (i > 0 && (n - i) % 3 == 0) buf[o++] = ',';
        buf[o++] = digits[i];
    }
    buf[o] = '\0';
    return buf;
}

static const char *duration(long secs, char *buf, size_t sz) {
    long h = secs / 3600, m = (secs % 3600) / 60, s = secs % 60;
    if (h)      snprintf(buf, sz, "%ldh%02ldm", h, m);
    else if (m) snprintf(buf, sz, "%ldm%02lds", m, s);
    else        snprintf(buf, sz, "%lds", s);
    return buf;
}

// ---------------------------------------------------------------- the hunt

int main(int argc, char **argv) {
    const char *tok = getenv("TELEGRAM_BOT_TOKEN");
    const char *cht = getenv("TELEGRAM_CHAT_ID");
    g_token = (tok && *tok) ? tok : TELEGRAM_TOKEN_DEFAULT;
    g_chat  = (cht && *cht) ? cht : TELEGRAM_CHAT_DEFAULT;

    // Validate by shape, not by comparing against TELEGRAM_TOKEN_DEFAULT: a
    // BareMetal build bakes the real token *into* that macro, so comparing
    // against it would reject exactly the builds that are correctly configured.
    // Every Telegram bot token looks like <digits>:<base64ish>.
    if (!strchr(g_token, ':')) {
        fprintf(stderr, "[!] no usable bot token (got %.12s...): set TELEGRAM_BOT_TOKEN, "
                        "or bake one into TELEGRAM_TOKEN_DEFAULT for BareMetal.\n", g_token);
        return 1;
    }
    snprintf(g_url, sizeof(g_url), "https://api.telegram.org/bot%s/sendMessage", g_token);

    // --seconds N stops after N seconds; without it the hunt runs forever.
    long run_for = 0;
    for (int i = 1; i < argc - 1; i++)
        if (strcmp(argv[i], "--seconds") == 0) run_for = strtol(argv[i + 1], NULL, 10);

    curl_global_init(CURL_GLOBAL_DEFAULT);

    uint64_t k          = START_AT;   // candidate pair is (6k-1, 6k+1)
    uint64_t checked    = 0;          // pairs tested
    uint64_t twins      = 0;          // twin pairs found
    uint64_t last_twin  = 0;          // lower member of the previous pair
    uint64_t record_gap = 0;          // biggest distance between consecutive pairs
    uint64_t hb_mark    = 0;          // `checked` at the last heartbeat

    time_t started = time(NULL);
    time_t last_hb = started;

    char b1[32], b2[32], b3[32], b4[32], b5[32], msg[1024];

    snprintf(msg, sizeof(msg),
             "\xF0\x9F\x94\xAD Prime hunter online.\n"
             "Searching for twin primes from %s upward.\n"
             "Records posted as they fall; heartbeat every %d min.",
             commas(6 * START_AT - 1, b1, sizeof(b1)), HEARTBEAT_SECONDS / 60);
    telegram_send(msg);
    printf("[+] hunting from %s\n", commas(6 * START_AT - 1, b1, sizeof(b1)));

    for (;;) {
        uint64_t p = 6 * k - 1, q = 6 * k + 1;   // every twin pair but (3,5)
                                                 // has this shape
        checked++;

        if (is_prime(p) && is_prime(q)) {
            twins++;
            uint64_t gap = last_twin ? p - last_twin : 0;

            // A record only counts once there is a previous pair to measure from,
            // and it is only worth announcing once it clears the silence floor.
            // A gap that merely ties the record is not a record.
            int is_record = (last_twin != 0 && gap > record_gap);
            if (is_record) record_gap = gap;

            if (is_record && gap >= RECORD_FLOOR) {
                time_t now = time(NULL);
                snprintf(msg, sizeof(msg),
                         "\xE2\x9C\xA8 New record gap: %s\n"
                         "between twin pairs (%s, %s) and (%s, %s)\n"
                         "twins found: %llu \xC2\xB7 uptime %s",
                         commas(gap, b1, sizeof(b1)),
                         commas(last_twin, b2, sizeof(b2)),
                         commas(last_twin + 2, b3, sizeof(b3)),
                         commas(p, b4, sizeof(b4)),
                         commas(p + 2, b5, sizeof(b5)),
                         (unsigned long long)twins,
                         duration((long)(now - started), (char[16]){0}, 16));
                printf("[*] record gap %llu at %llu\n",
                       (unsigned long long)gap, (unsigned long long)p);
                telegram_send(msg);
            }
            last_twin = p;
        }

        // Heartbeat: whichever of the two thresholds trips first.
        time_t now = time(NULL);
        long elapsed_hb = (long)(now - last_hb);
        if (elapsed_hb >= HEARTBEAT_SECONDS || checked - hb_mark >= HEARTBEAT_EVERY) {
            long total = (long)(now - started);
            uint64_t rate = total > 0 ? checked / (uint64_t)total : checked;

            snprintf(msg, sizeof(msg),
                     "\xF0\x9F\x94\x8D Still hunting.\n"
                     "searched to: %s\n"
                     "twin pairs:  %s\n"
                     "record gap:  %s\n"
                     "rate:        %s pairs/sec \xC2\xB7 uptime %s",
                     commas(q, b1, sizeof(b1)),
                     commas(twins, b2, sizeof(b2)),
                     commas(record_gap, b3, sizeof(b3)),
                     commas(rate, b4, sizeof(b4)),
                     duration(total, (char[16]){0}, 16));
            printf("[*] heartbeat: searched to %llu, %llu twins\n",
                   (unsigned long long)q, (unsigned long long)twins);
            telegram_send(msg);

            last_hb = now;
            hb_mark = checked;
        }

        if (run_for && (long)(now - started) >= run_for) {
            snprintf(msg, sizeof(msg),
                     "\xF0\x9F\x9B\x91 Hunt stopped after %s.\n"
                     "searched to %s \xC2\xB7 %s twin pairs \xC2\xB7 record gap %s",
                     duration((long)(now - started), (char[16]){0}, 16),
                     commas(q, b1, sizeof(b1)),
                     commas(twins, b2, sizeof(b2)),
                     commas(record_gap, b3, sizeof(b3)));
            telegram_send(msg);
            printf("[+] stopped: %llu pairs checked, %llu twins, %ld posts ok / %ld failed\n",
                   (unsigned long long)checked, (unsigned long long)twins,
                   g_posts_ok, g_posts_failed);
            break;
        }

        k++;
    }

    curl_global_cleanup();
    return 0;
}
