#!/usr/bin/env python3
"""TSPLIB EUC_2D .tsp -> a C header with the instance compiled in.

BareMetal has no filesystem, so the coordinates must live in the binary.
Only EUC_2D is accepted: TSPLIB defines its distance as nint(sqrt(dx^2+dy^2)),
and the published optima do not reproduce under any other rounding.
"""
import sys, re

def parse(path):
    name, dim, etype, coords, in_coords = None, None, None, [], False
    for line in open(path):
        line = line.strip()
        if not line or line == "EOF":
            continue
        if in_coords:
            parts = line.split()
            if len(parts) >= 3:
                coords.append((float(parts[1]), float(parts[2])))
            continue
        if line.startswith("NODE_COORD_SECTION"):
            in_coords = True
        elif ":" in line:
            k, v = (s.strip() for s in line.split(":", 1))
            if k == "NAME": name = v
            elif k == "DIMENSION": dim = int(v)
            elif k == "EDGE_WEIGHT_TYPE": etype = v
    return name, dim, etype, coords

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_instance.py <file.tsp> <optimum>")
    path, optimum = sys.argv[1], int(sys.argv[2])
    name, dim, etype, coords = parse(path)
    if etype != "EUC_2D":
        sys.exit(f"error: EDGE_WEIGHT_TYPE must be EUC_2D, got {etype!r}")
    if dim != len(coords):
        sys.exit(f"error: DIMENSION {dim} but {len(coords)} coordinates")
    # Coordinates are stored as int32. TSPLIB EUC_2D coords are integral in
    # every instance used here; a fractional one would change the distances,
    # so refuse rather than silently truncate.
    for x, y in coords:
        if x != int(x) or y != int(y):
            sys.exit(f"error: non-integral coordinate ({x}, {y})")
    guard = re.sub(r"\W", "_", name).upper()
    out = [f"/* Generated by gen_instance.py from {name}.tsp. Do not edit. */",
           f"#ifndef ACO_INSTANCE_{guard}_H", f"#define ACO_INSTANCE_{guard}_H",
           "", f'#define ACO_NAME "{name}"', f"#define ACO_N {dim}",
           f"#define ACO_OPTIMUM {optimum}", "",
           "static const int32_t ACO_XY[ACO_N][2] = {"]
    for x, y in coords:
        out.append(f"    {{{int(x)}, {int(y)}}},")
    out += ["};", "", "#endif"]
    print("\n".join(out))

if __name__ == "__main__":
    main()
