#!/usr/bin/env python3
"""Emit presigned S3 URLs for the swarm's migration register, as a C header.

Why presigned URLs rather than an S3 client in the guest: BareMetal has no
environment and no credential store, and SigV4 signing would mean HMAC-SHA256
plumbing inside the unikernel. A presigned URL carries its own credential in
the query string, so the worker performs a plain HTTPS GET or PUT and needs no
signing code at all -- which also keeps the image small.

Each worker owns one key and never writes another's, so there is no
last-writer-wins race: a worker publishes best-w<self> and reads its peers,
taking the maximum client-side.

The generated header is a bearer capability. Do not commit it.
"""
import sys, boto3
from botocore.config import Config

EXPIRES = 604800   # 7 days, the SigV4 maximum for long-term IAM credentials

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: gen_register_urls.py <bucket> <n-workers> <out.h>")
    bucket, n, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    s3 = boto3.client("s3", region_name="us-east-1",
                      config=Config(signature_version="s3v4"))
    lines = ["/* Generated by gen_register_urls.py. SECRET -- do not commit. */",
             "#ifndef ACO_REGISTER_URLS_H", "#define ACO_REGISTER_URLS_H", "",
             f"#define REG_WORKERS {n}", ""]
    for w in range(n):
        put = s3.generate_presigned_url("put_object",
                Params={"Bucket": bucket, "Key": f"best-w{w}"}, ExpiresIn=EXPIRES)
        lines.append(f'#define REG_PUT_W{w} "{put}"')
    lines.append("")
    gets = []
    for w in range(n):
        get = s3.generate_presigned_url("get_object",
                Params={"Bucket": bucket, "Key": f"best-w{w}"}, ExpiresIn=EXPIRES)
        gets.append(f'    "{get}"')
    lines.append("static const char *REG_GET_URL[REG_WORKERS] = {")
    lines.append(",\n".join(gets))
    lines.append("};")
    lines.append("")
    lines.append("static const char *REG_PUT_URL[REG_WORKERS] = {")
    lines.append(",\n".join(f"    REG_PUT_W{w}" for w in range(n)))
    lines.append("};")
    lines += ["", "#endif"]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"{out}: {n} workers, expires in {EXPIRES}s")

if __name__ == "__main__":
    main()
