#!/bin/bash
# mkslice.sh -- sieve a range of multipliers and emit it as a C header for
# cc_worker.
#
# BareMetal hands main() no argv, so a worker's parameters cannot be passed at
# run time: they are compiled in. This turns one sieved range into one
# cc_slice.h, and therefore into one worker image.
#
# The ranges handed to different workers must not overlap, or two instances
# spend their time proving the same multipliers composite. This script does not
# enforce that -- the caller allocates the ranges; see build-worker.sh.
#
#   ./mkslice.sh <slice-id> <m-start> <m-count> <out.h>
#
set -euo pipefail

SLICE_ID="${1:?usage: mkslice.sh <slice-id> <m-start> <m-count> <out.h>}"
M_START="${2:?}"
M_COUNT="${3:?}"
OUT="${4:?}"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
K="${K:-6}"
PRIMORIAL="${PRIMORIAL:-2357}"
J="${J:-1}"
DEPTH="${DEPTH:-1000000000}"

GMPDIR="$(brew --prefix gmp 2>/dev/null || echo /usr)"
SIEVE="${SIEVE:-/tmp/cc_sieve_mkslice}"
if [ ! -x "$SIEVE" ] || [ "$REPO/cc_sieve.c" -nt "$SIEVE" ]; then
	gcc -O2 -o "$SIEVE" "$REPO/cc_sieve.c" \
		-I"$GMPDIR/include" -L"$GMPDIR/lib" -lgmp -lm
fi

# Never generate a slice from a sieve that has not just proven itself. A
# wrongly-sieved slice produces a worker that runs perfectly and searches the
# wrong candidates, which is indistinguishable from bad luck.
"$SIEVE" --selftest >/dev/null 2>&1 || { echo "cc_sieve selftest FAILED" >&2; exit 1; }

echo "sieving $SLICE_ID: m=[$M_START,$((M_START + M_COUNT))) depth=$DEPTH" >&2
TMP=$(mktemp)
"$SIEVE" --k "$K" --primorial "$PRIMORIAL" --j "$J" \
         --m-start "$M_START" --m-count "$M_COUNT" --depth "$DEPTH" \
         --list --quiet 2>/dev/null | awk '/^M /{print $2}' > "$TMP"

N=$(wc -l < "$TMP" | tr -d ' ')
[ "$N" -gt 0 ] || { echo "no survivors -- refusing to emit an empty slice" >&2; rm -f "$TMP"; exit 1; }

{
	echo "/* Generated by mkslice.sh -- do not edit."
	echo " * slice $SLICE_ID, m in [$M_START, $((M_START + M_COUNT))), depth $DEPTH"
	echo " * $N survivors of $M_COUNT multipliers"
	echo " */"
	echo "#define SLICE_ID        \"$SLICE_ID\""
	echo "#define SLICE_M_LO      ${M_START}ULL"
	echo "#define SLICE_M_HI      $((M_START + M_COUNT))ULL"
	echo "#define SLICE_N         $N"
	echo "#define SLICE_PRIMORIAL $PRIMORIAL"
	echo "#define SLICE_K         $K"
	echo "#define SLICE_J         $J"
	echo "static const uint64_t slice_m[$N] = {"
	awk '{printf "\t%sULL,\n", $1}' "$TMP"
	echo "};"
} > "$OUT"

rm -f "$TMP"
echo "wrote $OUT: $N survivors from $M_COUNT multipliers ($(echo "scale=6; $N/$M_COUNT" | bc))" >&2
