/* Generated by gen_instance.py from tiny5.tsp. Do not edit. */
#ifndef ACO_INSTANCE_TINY5_H
#define ACO_INSTANCE_TINY5_H

#define ACO_NAME "tiny5"
#define ACO_N 5
#define ACO_OPTIMUM 0

static const int32_t ACO_XY[ACO_N][2] = {
    {0, 0},
    {3, 4},
    {10, 0},
    {0, 10},
    {6, 8},
};

#endif
